### ISSUE TITLE
pip install fails on macos with python3.6

### ISSUE THREAD

**Issue by ghost** [kingspp/bmark#1]
pip3 install log :=>
```
Collecting pmark
  Downloading https://files.pythonhosted.org/packages/f0/88/3f7abf187c2b17025f207da3d899621ef6dc6c40dd2d26b9b8d1f56ec63a/pmark-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Failed to load configuration file. Using default configs
    CRITICAL:pmark.config_manager:Configuration file path error. Please provide configuration file path: /private/tmp/pip-install-gv_t_zaw/pmark/pmark/config/module_config.json
    Traceback (most recent call last):
      File "/private/tmp/pip-install-gv_t_zaw/pmark/pmark/config_manager.py", line 74, in __init__
        MODULE_CONFIG_DATA = json.load(open(config_file_path), object_pairs_hook=OrderedDict)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/pip-install-gv_t_zaw/pmark/pmark/config/module_config.json'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-gv_t_zaw/pmark/setup.py", line 13, in <module>
        from pmark.metadata import metadata as md
      File "/private/tmp/pip-install-gv_t_zaw/pmark/pmark/__init__.py", line 41, in <module>
        from pmark.config_manager import MODULE_CONFIG, MODULE_CONFIG_DATA
      File "/private/tmp/pip-install-gv_t_zaw/pmark/pmark/config_manager.py", line 118, in <module>
        MODULE_CONFIG = ConfigManager(config_file_path=ConfigPath).get_config_manager()
      File "/private/tmp/pip-install-gv_t_zaw/pmark/pmark/__init__.py", line 28, in __call__
        cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
      File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/typeguard.py", line 494, in wrapper
        retval = func(*args, **kwargs)
      File "/private/tmp/pip-install-gv_t_zaw/pmark/pmark/config_manager.py", line 79, in __init__
        'Configuration file path error. Please provide configuration file path: ' + config_file_path, e)
    Exception: ('Configuration file path error. Please provide configuration file path: /private/tmp/pip-install-gv_t_zaw/pmark/pmark/config/module_config.json', FileNotFoundError(2, 'No such file or directory'))

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-gv_t_zaw/pmark/
```

**Comment by kingspp** [comment]
Fixed with latest release
